### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Felix83000**

### CODE REVIEW

**Comment by joachimmetz** [comment]
Looks like this project is also redistributing copyrighted material of third parties like SANS. This should be covered in the license/copyright information as well

**Comment by Felix83000** [comment]
> Looks like this project is also redistributing copyrighted material of third parties like SANS. This should be covered in the license/copyright information as well

Hi,

No redistribution. Just install command lines. Third parties materials are not embedded in FAST. It is several install scripts basically.

Best regards

**Comment by joachimmetz** [comment]
@Felix83000 this project is (re) distributing copyrighted by third parties e.g. https://github.com/thalesgroup-cert/FAST/blob/main/Documentation/CheatSheet%20SANS/General%20IT%20Security/Python%203%20Essentials.pdf

**Comment by Felix83000** [comment]
All right. thanks @joachimmetz

**Pull request merged**
